// MyPlugin.svelte
<div id="webcrumbs"><div class="min-h-[800px] bg-white rounded-lg shadow-lg"> <header class="bg-neutral-200 p-6"> <h1 class="text-4xl font-title text-primary-950 text-center sm:text-left"> Software Engineer Portfolio </h1> <p class="mt-2 text-neutral-700 text-center sm:text-left"> Showcasing my projects, experiences, and journey in tech. </p> </header> <div class="flex flex-col sm:flex-row gap-6 p-6"> <aside class="sm:w-1/4"> <section class="flex flex-col gap-4 items-center sm:items-start"> <div class="mx-auto rounded-full w-[150px] h-[150px] perspective-1000" style="position:relative"> <div class="relative group transition-transform" style="width:150px;height:150px;perspective:800px"> <div class="transition-transform duration-500 group-hover:transition-none" style="width:100%;height:100%;background-image:url(https://tools-api.webcrumbs.org/image-placeholder/300/300/avatars/1);background-size:contain;background-position:center;background-repeat:no-repeat;border-radius:50%;box-shadow:0 4px 8px rgba(0, 0, 0, 0.2);transform-style:preserve-3d" data-handler="handler_0"> <div class="absolute inset-0 pointer-events-none rounded-full transition-opacity opacity-0 group-hover:opacity-100" style="box-shadow:0 0 15px 5px rgba(255, 255, 255, 0.5)"></div> </div> </div> </div> <h2 class="text-2xl font-semibold text-center text-neutral-950"> John Doe </h2> <ul class="flex justify-center mt-4 gap-3"> <i class="fa-brands fa-github text-neutral-950 text-xl"></i> <i class="fa-brands fa-linkedin text-neutral-950 text-xl"></i> <i class="material-symbols-outlined text-neutral-950 text-xl"> email </i> </ul> </section> <p class="text-center text-neutral-600"> Passionate about creating elegant and efficient solutions. </p> </aside> <main class="flex-1"> <section class="mb-6"> <h3 class="text-2xl font-title text-primary-950">About Me</h3> <p class="mt-4 text-neutral-700 leading-relaxed"> I am a software engineer with a focus on building scalable web applications. I thrive on solving complex problems and turning ideas into reality. </p> </section> <section class="mb-6"> <h3 class="text-2xl font-title text-primary-950">Projects</h3> <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 mt-4"> <div class="bg-neutral-100 rounded-md p-4 transition-transform duration-300 hover:scale-[1.05] hover:translate-y-[-5px] hover:shadow-xl"> <img src="https://tools-api.webcrumbs.org/image-placeholder/300/200/shapes/1" alt="Project A" class="w-full h-[120px] rounded-md object-cover mb-2"/> <h4 class="text-lg font-medium text-neutral-950">Project A</h4> <p class="mt-2 text-neutral-600"> A web application for managing tasks efficiently. </p> </div> <div class="bg-neutral-100 rounded-md p-4 transition-transform duration-300 hover:scale-[1.05] hover:translate-y-[-5px] hover:shadow-xl"> <img src="https://tools-api.webcrumbs.org/image-placeholder/300/200/shapes/2" alt="Project B" class="w-full h-[120px] rounded-md object-cover mb-2"/> <h4 class="text-lg font-medium text-neutral-950">Project B</h4> <p class="mt-2 text-neutral-600"> An innovative platform for online learning. </p> </div> <div class="bg-neutral-100 rounded-md p-4 transition-transform duration-300 hover:scale-[1.05] hover:translate-y-[-5px] hover:shadow-xl"> <img src="https://tools-api.webcrumbs.org/image-placeholder/300/200/shapes/3" alt="Project C" class="w-full h-[120px] rounded-md object-cover mb-2"/> <h4 class="text-lg font-medium text-neutral-950">Project C</h4> <p class="mt-2 text-neutral-600"> A mobile app for tracking fitness goals. </p> </div> </div> </section> <section class="mb-6"> <h3 class="text-2xl font-title text-primary-950">Skills</h3> <div class="flex flex-wrap gap-4 mt-4"> <div class="bg-primary-100 text-primary-950 font-medium py-2 px-4 rounded-full shadow-md transition-transform duration-300 hover:scale-[1.1] hover:bg-primary-200"> HTML </div><div class="bg-primary-100 text-primary-950 font-medium py-2 px-4 rounded-full shadow-md transition-transform duration-300 hover:scale-[1.1] hover:bg-primary-200"> CSS </div><div class="bg-primary-100 text-primary-950 font-medium py-2 px-4 rounded-full shadow-md transition-transform duration-300 hover:scale-[1.1] hover:bg-primary-200"> JavaScript </div><div class="bg-primary-100 text-primary-950 font-medium py-2 px-4 rounded-full shadow-md transition-transform duration-300 hover:scale-[1.1] hover:bg-primary-200"> React </div><div class="bg-primary-100 text-primary-950 font-medium py-2 px-4 rounded-full shadow-md transition-transform duration-300 hover:scale-[1.1] hover:bg-primary-200"> Node.js </div><div class="bg-primary-100 text-primary-950 font-medium py-2 px-4 rounded-full shadow-md transition-transform duration-300 hover:scale-[1.1] hover:bg-primary-200"> Python </div><div class="bg-primary-100 text-primary-950 font-medium py-2 px-4 rounded-full shadow-md transition-transform duration-300 hover:scale-[1.1] hover:bg-primary-200"> Django </div> </div> </section> <section> <h3 class="text-2xl font-title text-primary-950">Experiences</h3> <ul class="mt-4 space-y-4"> <li class="bg-neutral-100 rounded-md p-4"> <p class="font-bold text-neutral-950">Software Engineer</p> <p class="text-neutral-600">XYZ Company | Jan 2020 - Present</p> <p class="mt-2 text-neutral-700"> Leading the development of a high-performing team. </p> </li> <li class="bg-neutral-100 rounded-md p-4"> <p class="font-bold text-neutral-950">Junior Developer</p> <p class="text-neutral-600">ABC Corp | May 2018 - Dec 2019</p> <p class="mt-2 text-neutral-700"> Contributed to frontend optimizations and design. </p> </li> </ul> </section> </main> </div> <footer class="bg-neutral-200 p-6 text-center"> <p class="text-neutral-600">© 2023 John Doe. All rights reserved.</p> </footer> </div></div>

<style>
  @import url(https://fonts.googleapis.com/css2?family=Lato&display=swap);
  
  @import url(https://fonts.googleapis.com/css2?family=Open+Sans&display=swap);
  
  @import url(https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200);
  
  @import url(https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css);
  
  /*! tailwindcss v3.4.11 | MIT License | https://tailwindcss.com*/
  *,
  :after,
  :before {
    border: 0 solid #e5e7eb;
    box-sizing: border-box;
  }
  :after,
  :before {
    --tw-content: "";
  }
  :host,
  html {
    line-height: 1.5;
    -webkit-text-size-adjust: 100%;
    font-family:
      Open Sans,
      ui-sans-serif,
      system-ui,
      sans-serif,
      Apple Color Emoji,
      Segoe UI Emoji,
      Segoe UI Symbol,
      Noto Color Emoji;
    font-feature-settings: normal;
    font-variation-settings: normal;
    -moz-tab-size: 4;
    tab-size: 4;
    -webkit-tap-highlight-color: transparent;
  }
  body {
    line-height: inherit;
    margin: 0;
  }
  hr {
    border-top-width: 1px;
    color: inherit;
    height: 0;
  }
  abbr:where([title]) {
    text-decoration: underline dotted;
  }
  h1,
  h2,
  h3,
  h4,
  h5,
  h6 {
    font-size: inherit;
    font-weight: inherit;
  }
  a {
    color: inherit;
    text-decoration: inherit;
  }
  b,
  strong {
    font-weight: bolder;
  }
  code,
  kbd,
  pre,
  samp {
    font-family:
      ui-monospace,
      SFMono-Regular,
      Menlo,
      Monaco,
      Consolas,
      Liberation Mono,
      Courier New,
      monospace;
    font-feature-settings: normal;
    font-size: 1em;
    font-variation-settings: normal;
  }
  small {
    font-size: 80%;
  }
  sub,
  sup {
    font-size: 75%;
    line-height: 0;
    position: relative;
    vertical-align: baseline;
  }
  sub {
    bottom: -0.25em;
  }
  sup {
    top: -0.5em;
  }
  table {
    border-collapse: collapse;
    border-color: inherit;
    text-indent: 0;
  }
  button,
  input,
  optgroup,
  select,
  textarea {
    color: inherit;
    font-family: inherit;
    font-feature-settings: inherit;
    font-size: 100%;
    font-variation-settings: inherit;
    font-weight: inherit;
    letter-spacing: inherit;
    line-height: inherit;
    margin: 0;
    padding: 0;
  }
  button,
  select {
    text-transform: none;
  }
  button,
  input:where([type="button"]),
  input:where([type="reset"]),
  input:where([type="submit"]) {
    -webkit-appearance: button;
    background-color: transparent;
    background-image: none;
  }
  :-moz-focusring {
    outline: auto;
  }
  :-moz-ui-invalid {
    box-shadow: none;
  }
  progress {
    vertical-align: baseline;
  }
  ::-webkit-inner-spin-button,
  ::-webkit-outer-spin-button {
    height: auto;
  }
  [type="search"] {
    -webkit-appearance: textfield;
    outline-offset: -2px;
  }
  ::-webkit-search-decoration {
    -webkit-appearance: none;
  }
  ::-webkit-file-upload-button {
    -webkit-appearance: button;
    font: inherit;
  }
  summary {
    display: list-item;
  }
  blockquote,
  dd,
  dl,
  figure,
  h1,
  h2,
  h3,
  h4,
  h5,
  h6,
  hr,
  p,
  pre {
    margin: 0;
  }
  fieldset {
    margin: 0;
  }
  fieldset,
  legend {
    padding: 0;
  }
  menu,
  ol,
  ul {
    list-style: none;
    margin: 0;
    padding: 0;
  }
  dialog {
    padding: 0;
  }
  textarea {
    resize: vertical;
  }
  input::placeholder,
  textarea::placeholder {
    color: #9ca3af;
    opacity: 1;
  }
  [role="button"],
  button {
    cursor: pointer;
  }
  :disabled {
    cursor: default;
  }
  audio,
  canvas,
  embed,
  iframe,
  img,
  object,
  svg,
  video {
    display: block;
    vertical-align: middle;
  }
  img,
  video {
    height: auto;
    max-width: 100%;
  }
  [hidden] {
    display: none;
  }
  *,
  :after,
  :before {
    --tw-border-spacing-x: 0;
    --tw-border-spacing-y: 0;
    --tw-translate-x: 0;
    --tw-translate-y: 0;
    --tw-rotate: 0;
    --tw-skew-x: 0;
    --tw-skew-y: 0;
    --tw-scale-x: 1;
    --tw-scale-y: 1;
    --tw-pan-x: ;
    --tw-pan-y: ;
    --tw-pinch-zoom: ;
    --tw-scroll-snap-strictness: proximity;
    --tw-gradient-from-position: ;
    --tw-gradient-via-position: ;
    --tw-gradient-to-position: ;
    --tw-ordinal: ;
    --tw-slashed-zero: ;
    --tw-numeric-figure: ;
    --tw-numeric-spacing: ;
    --tw-numeric-fraction: ;
    --tw-ring-inset: ;
    --tw-ring-offset-width: 0px;
    --tw-ring-offset-color: #fff;
    --tw-ring-color: rgba(59, 130, 246, 0.5);
    --tw-ring-offset-shadow: 0 0 #0000;
    --tw-ring-shadow: 0 0 #0000;
    --tw-shadow: 0 0 #0000;
    --tw-shadow-colored: 0 0 #0000;
    --tw-blur: ;
    --tw-brightness: ;
    --tw-contrast: ;
    --tw-grayscale: ;
    --tw-hue-rotate: ;
    --tw-invert: ;
    --tw-saturate: ;
    --tw-sepia: ;
    --tw-drop-shadow: ;
    --tw-backdrop-blur: ;
    --tw-backdrop-brightness: ;
    --tw-backdrop-contrast: ;
    --tw-backdrop-grayscale: ;
    --tw-backdrop-hue-rotate: ;
    --tw-backdrop-invert: ;
    --tw-backdrop-opacity: ;
    --tw-backdrop-saturate: ;
    --tw-backdrop-sepia: ;
    --tw-contain-size: ;
    --tw-contain-layout: ;
    --tw-contain-paint: ;
    --tw-contain-style: ;
  }
  ::backdrop {
    --tw-border-spacing-x: 0;
    --tw-border-spacing-y: 0;
    --tw-translate-x: 0;
    --tw-translate-y: 0;
    --tw-rotate: 0;
    --tw-skew-x: 0;
    --tw-skew-y: 0;
    --tw-scale-x: 1;
    --tw-scale-y: 1;
    --tw-pan-x: ;
    --tw-pan-y: ;
    --tw-pinch-zoom: ;
    --tw-scroll-snap-strictness: proximity;
    --tw-gradient-from-position: ;
    --tw-gradient-via-position: ;
    --tw-gradient-to-position: ;
    --tw-ordinal: ;
    --tw-slashed-zero: ;
    --tw-numeric-figure: ;
    --tw-numeric-spacing: ;
    --tw-numeric-fraction: ;
    --tw-ring-inset: ;
    --tw-ring-offset-width: 0px;
    --tw-ring-offset-color: #fff;
    --tw-ring-color: rgba(59, 130, 246, 0.5);
    --tw-ring-offset-shadow: 0 0 #0000;
    --tw-ring-shadow: 0 0 #0000;
    --tw-shadow: 0 0 #0000;
    --tw-shadow-colored: 0 0 #0000;
    --tw-blur: ;
    --tw-brightness: ;
    --tw-contrast: ;
    --tw-grayscale: ;
    --tw-hue-rotate: ;
    --tw-invert: ;
    --tw-saturate: ;
    --tw-sepia: ;
    --tw-drop-shadow: ;
    --tw-backdrop-blur: ;
    --tw-backdrop-brightness: ;
    --tw-backdrop-contrast: ;
    --tw-backdrop-grayscale: ;
    --tw-backdrop-hue-rotate: ;
    --tw-backdrop-invert: ;
    --tw-backdrop-opacity: ;
    --tw-backdrop-saturate: ;
    --tw-backdrop-sepia: ;
    --tw-contain-size: ;
    --tw-contain-layout: ;
    --tw-contain-paint: ;
    --tw-contain-style: ;
  }
  #webcrumbs .pointer-events-none {
    pointer-events: none;
  }
  #webcrumbs .absolute {
    position: absolute;
  }
  #webcrumbs .relative {
    position: relative;
  }
  #webcrumbs .inset-0 {
    inset: 0;
  }
  #webcrumbs .mx-auto {
    margin-left: auto;
    margin-right: auto;
  }
  #webcrumbs .mb-2 {
    margin-bottom: 8px;
  }
  #webcrumbs .mb-6 {
    margin-bottom: 24px;
  }
  #webcrumbs .mt-2 {
    margin-top: 8px;
  }
  #webcrumbs .mt-4 {
    margin-top: 16px;
  }
  #webcrumbs .flex {
    display: flex;
  }
  #webcrumbs .grid {
    display: grid;
  }
  #webcrumbs .h-\[120px\] {
    height: 120px;
  }
  #webcrumbs .h-\[150px\] {
    height: 150px;
  }
  #webcrumbs .min-h-\[800px\] {
    min-height: 800px;
  }
  #webcrumbs .w-\[150px\] {
    width: 150px;
  }
  #webcrumbs .w-full {
    width: 100%;
  }
  #webcrumbs .flex-1 {
    flex: 1 1 0%;
  }
  #webcrumbs .grid-cols-1 {
    grid-template-columns: repeat(1, minmax(0, 1fr));
  }
  #webcrumbs .flex-row {
    flex-direction: row;
  }
  #webcrumbs .flex-col {
    flex-direction: column;
  }
  #webcrumbs .flex-wrap {
    flex-wrap: wrap;
  }
  #webcrumbs .items-center {
    align-items: center;
  }
  #webcrumbs .justify-center {
    justify-content: center;
  }
  #webcrumbs .justify-between {
    justify-content: space-between;
  }
  #webcrumbs .gap-3 {
    gap: 12px;
  }
  #webcrumbs .gap-4 {
    gap: 16px;
  }
  #webcrumbs .gap-6 {
    gap: 24px;
  }
  #webcrumbs :is(.space-y-4 > :not([hidden]) ~ :not([hidden])) {
    --tw-space-y-reverse: 0;
    margin-bottom: calc(16px * var(--tw-space-y-reverse));
    margin-top: calc(16px * (1 - var(--tw-space-y-reverse)));
  }
  #webcrumbs .rounded-full {
    border-radius: 9999px;
  }
  #webcrumbs .rounded-lg {
    border-radius: 24px;
  }
  #webcrumbs .rounded-md {
    border-radius: 18px;
  }
  #webcrumbs .bg-neutral-100 {
    --tw-bg-opacity: 1;
    background-color: rgb(238 238 238 / var(--tw-bg-opacity));
  }
  #webcrumbs .bg-neutral-200 {
    --tw-bg-opacity: 1;
    background-color: rgb(224 224 224 / var(--tw-bg-opacity));
  }
  #webcrumbs .bg-primary-100 {
    --tw-bg-opacity: 1;
    background-color: rgb(233 229 255 / var(--tw-bg-opacity));
  }
  #webcrumbs .bg-white {
    --tw-bg-opacity: 1;
    background-color: rgb(255 255 255 / var(--tw-bg-opacity));
  }
  #webcrumbs .object-cover {
    object-fit: cover;
  }
  #webcrumbs .p-4 {
    padding: 16px;
  }
  #webcrumbs .p-6 {
    padding: 24px;
  }
  #webcrumbs .px-4 {
    padding-left: 16px;
    padding-right: 16px;
  }
  #webcrumbs .py-2 {
    padding-bottom: 8px;
    padding-top: 8px;
  }
  #webcrumbs .text-center {
    text-align: center;
  }
  #webcrumbs .font-title {
    font-family:
      Lato,
      ui-sans-serif,
      system-ui,
      sans-serif,
      Apple Color Emoji,
      Segoe UI Emoji,
      Segoe UI Symbol,
      Noto Color Emoji;
  }
  #webcrumbs .text-2xl {
    font-size: 24px;
    line-height: 31.200000000000003px;
  }
  #webcrumbs .text-4xl {
    font-size: 36px;
    line-height: 41.4px;
  }
  #webcrumbs .text-lg {
    font-size: 18px;
    line-height: 27px;
  }
  #webcrumbs .text-xl {
    font-size: 20px;
    line-height: 28px;
  }
  #webcrumbs .font-bold {
    font-weight: 700;
  }
  #webcrumbs .font-medium {
    font-weight: 500;
  }
  #webcrumbs .font-semibold {
    font-weight: 600;
  }
  #webcrumbs .leading-relaxed {
    line-height: 1.625;
  }
  #webcrumbs .text-neutral-600 {
    --tw-text-opacity: 1;
    color: rgb(127 127 127 / var(--tw-text-opacity));
  }
  #webcrumbs .text-neutral-700 {
    --tw-text-opacity: 1;
    color: rgb(103 103 103 / var(--tw-text-opacity));
  }
  #webcrumbs .text-neutral-950 {
    --tw-text-opacity: 1;
    color: rgb(40 40 40 / var(--tw-text-opacity));
  }
  #webcrumbs .text-primary-950 {
    --tw-text-opacity: 1;
    color: rgb(34 1 116 / var(--tw-text-opacity));
  }
  #webcrumbs .opacity-0 {
    opacity: 0;
  }
  #webcrumbs .shadow-lg {
    --tw-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1),
      0 4px 6px -4px rgba(0, 0, 0, 0.1);
    --tw-shadow-colored: 0 10px 15px -3px var(--tw-shadow-color),
      0 4px 6px -4px var(--tw-shadow-color);
  }
  #webcrumbs .shadow-lg,
  #webcrumbs .shadow-md {
    box-shadow: var(--tw-ring-offset-shadow, 0 0 #0000),
      var(--tw-ring-shadow, 0 0 #0000), var(--tw-shadow);
  }
  #webcrumbs .shadow-md {
    --tw-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1),
      0 2px 4px -2px rgba(0, 0, 0, 0.1);
    --tw-shadow-colored: 0 4px 6px -1px var(--tw-shadow-color),
      0 2px 4px -2px var(--tw-shadow-color);
  }
  #webcrumbs .transition-opacity {
    transition-duration: 0.15s;
    transition-property: opacity;
    transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
  }
  #webcrumbs .transition-transform {
    transition-duration: 0.15s;
    transition-property: transform;
    transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
  }
  #webcrumbs .duration-300 {
    transition-duration: 0.3s;
  }
  #webcrumbs .duration-500 {
    transition-duration: 0.5s;
  }
  #webcrumbs {
    font-family: Open Sans !important;
    font-size: 16px !important;
  }
  #webcrumbs :is(.bg-neutral-100) {
    color: rgba(0, 0, 0, 0.9) !important;
  }
  #webcrumbs :is(.bg-neutral-200) {
    color: rgba(0, 0, 0, 0.9) !important;
  }
  #webcrumbs :is(.bg-primary-100) {
    color: rgba(0, 0, 0, 0.9) !important;
  }
  #webcrumbs .hover\:translate-y-\[-5px\]:hover {
    --tw-translate-y: -5px;
  }
  #webcrumbs .hover\:scale-\[1\.05\]:hover,
  #webcrumbs .hover\:translate-y-\[-5px\]:hover {
    transform: translate(var(--tw-translate-x), var(--tw-translate-y))
      rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y))
      scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));
  }
  #webcrumbs .hover\:scale-\[1\.05\]:hover {
    --tw-scale-x: 1.05;
    --tw-scale-y: 1.05;
  }
  #webcrumbs .hover\:scale-\[1\.1\]:hover {
    --tw-scale-x: 1.1;
    --tw-scale-y: 1.1;
    transform: translate(var(--tw-translate-x), var(--tw-translate-y))
      rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y))
      scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));
  }
  #webcrumbs .hover\:bg-primary-200:hover {
    --tw-bg-opacity: 1;
    background-color: rgb(213 207 255 / var(--tw-bg-opacity));
  }
  #webcrumbs .hover\:shadow-xl:hover {
    --tw-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1),
      0 8px 10px -6px rgba(0, 0, 0, 0.1);
    --tw-shadow-colored: 0 20px 25px -5px var(--tw-shadow-color),
      0 8px 10px -6px var(--tw-shadow-color);
    box-shadow: var(--tw-ring-offset-shadow, 0 0 #0000),
      var(--tw-ring-shadow, 0 0 #0000), var(--tw-shadow);
  }
  #webcrumbs :is(.group:hover .group-hover\:opacity-100) {
    opacity: 1;
  }
  #webcrumbs :is(.group:hover .group-hover\:transition-none) {
    transition-property: none;
  }
  @media (min-width: 640px) {
    #webcrumbs .sm\:w-1\/4 {
      width: 25%;
    }
    #webcrumbs .sm\:grid-cols-2 {
      grid-template-columns: repeat(2, minmax(0, 1fr));
    }
    #webcrumbs .sm\:flex-row {
      flex-direction: row;
    }
    #webcrumbs .sm\:items-start {
      align-items: flex-start;
    }
    #webcrumbs .sm\:text-left {
      text-align: left;
    }
  }
  @media (min-width: 1024px) {
    #webcrumbs .lg\:grid-cols-3 {
      grid-template-columns: repeat(3, minmax(0, 1fr));
    }
  }
  
</style>

// MyPlugin.vue
<template>
  <div id="webcrumbs"><div class="min-h-[800px] bg-white rounded-lg shadow-lg"> <header class="bg-neutral-200 p-6"> <h1 class="text-4xl font-title text-primary-950 text-center sm:text-left"> Software Engineer Portfolio </h1> <p class="mt-2 text-neutral-700 text-center sm:text-left"> Showcasing my projects, experiences, and journey in tech. </p> </header> <div class="flex flex-col sm:flex-row gap-6 p-6"> <aside class="sm:w-1/4"> <section class="flex flex-col gap-4 items-center sm:items-start"> <div class="mx-auto rounded-full w-[150px] h-[150px] perspective-1000" style="position:relative"> <div class="relative group transition-transform" style="width:150px;height:150px;perspective:800px"> <div class="transition-transform duration-500 group-hover:transition-none" style="width:100%;height:100%;background-image:url(https://tools-api.webcrumbs.org/image-placeholder/300/300/avatars/1);background-size:contain;background-position:center;background-repeat:no-repeat;border-radius:50%;box-shadow:0 4px 8px rgba(0, 0, 0, 0.2);transform-style:preserve-3d" data-handler="handler_0"> <div class="absolute inset-0 pointer-events-none rounded-full transition-opacity opacity-0 group-hover:opacity-100" style="box-shadow:0 0 15px 5px rgba(255, 255, 255, 0.5)"></div> </div> </div> </div> <h2 class="text-2xl font-semibold text-center text-neutral-950"> John Doe </h2> <ul class="flex justify-center mt-4 gap-3"> <i class="fa-brands fa-github text-neutral-950 text-xl"></i> <i class="fa-brands fa-linkedin text-neutral-950 text-xl"></i> <i class="material-symbols-outlined text-neutral-950 text-xl"> email </i> </ul> </section> <p class="text-center text-neutral-600"> Passionate about creating elegant and efficient solutions. </p> </aside> <main class="flex-1"> <section class="mb-6"> <h3 class="text-2xl font-title text-primary-950">About Me</h3> <p class="mt-4 text-neutral-700 leading-relaxed"> I am a software engineer with a focus on building scalable web applications. I thrive on solving complex problems and turning ideas into reality. </p> </section> <section class="mb-6"> <h3 class="text-2xl font-title text-primary-950">Projects</h3> <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 mt-4"> <div class="bg-neutral-100 rounded-md p-4 transition-transform duration-300 hover:scale-[1.05] hover:translate-y-[-5px] hover:shadow-xl"> <img src="https://tools-api.webcrumbs.org/image-placeholder/300/200/shapes/1" alt="Project A" class="w-full h-[120px] rounded-md object-cover mb-2"/> <h4 class="text-lg font-medium text-neutral-950">Project A</h4> <p class="mt-2 text-neutral-600"> A web application for managing tasks efficiently. </p> </div> <div class="bg-neutral-100 rounded-md p-4 transition-transform duration-300 hover:scale-[1.05] hover:translate-y-[-5px] hover:shadow-xl"> <img src="https://tools-api.webcrumbs.org/image-placeholder/300/200/shapes/2" alt="Project B" class="w-full h-[120px] rounded-md object-cover mb-2"/> <h4 class="text-lg font-medium text-neutral-950">Project B</h4> <p class="mt-2 text-neutral-600"> An innovative platform for online learning. </p> </div> <div class="bg-neutral-100 rounded-md p-4 transition-transform duration-300 hover:scale-[1.05] hover:translate-y-[-5px] hover:shadow-xl"> <img src="https://tools-api.webcrumbs.org/image-placeholder/300/200/shapes/3" alt="Project C" class="w-full h-[120px] rounded-md object-cover mb-2"/> <h4 class="text-lg font-medium text-neutral-950">Project C</h4> <p class="mt-2 text-neutral-600"> A mobile app for tracking fitness goals. </p> </div> </div> </section> <section class="mb-6"> <h3 class="text-2xl font-title text-primary-950">Skills</h3> <div class="flex flex-wrap gap-4 mt-4"> <div class="bg-primary-100 text-primary-950 font-medium py-2 px-4 rounded-full shadow-md transition-transform duration-300 hover:scale-[1.1] hover:bg-primary-200"> HTML </div><div class="bg-primary-100 text-primary-950 font-medium py-2 px-4 rounded-full shadow-md transition-transform duration-300 hover:scale-[1.1] hover:bg-primary-200"> CSS </div><div class="bg-primary-100 text-primary-950 font-medium py-2 px-4 rounded-full shadow-md transition-transform duration-300 hover:scale-[1.1] hover:bg-primary-200"> JavaScript </div><div class="bg-primary-100 text-primary-950 font-medium py-2 px-4 rounded-full shadow-md transition-transform duration-300 hover:scale-[1.1] hover:bg-primary-200"> React </div><div class="bg-primary-100 text-primary-950 font-medium py-2 px-4 rounded-full shadow-md transition-transform duration-300 hover:scale-[1.1] hover:bg-primary-200"> Node.js </div><div class="bg-primary-100 text-primary-950 font-medium py-2 px-4 rounded-full shadow-md transition-transform duration-300 hover:scale-[1.1] hover:bg-primary-200"> Python </div><div class="bg-primary-100 text-primary-950 font-medium py-2 px-4 rounded-full shadow-md transition-transform duration-300 hover:scale-[1.1] hover:bg-primary-200"> Django </div> </div> </section> <section> <h3 class="text-2xl font-title text-primary-950">Experiences</h3> <ul class="mt-4 space-y-4"> <li class="bg-neutral-100 rounded-md p-4"> <p class="font-bold text-neutral-950">Software Engineer</p> <p class="text-neutral-600">XYZ Company | Jan 2020 - Present</p> <p class="mt-2 text-neutral-700"> Leading the development of a high-performing team. </p> </li> <li class="bg-neutral-100 rounded-md p-4"> <p class="font-bold text-neutral-950">Junior Developer</p> <p class="text-neutral-600">ABC Corp | May 2018 - Dec 2019</p> <p class="mt-2 text-neutral-700"> Contributed to frontend optimizations and design. </p> </li> </ul> </section> </main> </div> <footer class="bg-neutral-200 p-6 text-center"> <p class="text-neutral-600">© 2023 John Doe. All rights reserved.</p> </footer> </div></div>
</template>

<style scoped>
  @import url(https://fonts.googleapis.com/css2?family=Lato&display=swap);
  
  @import url(https://fonts.googleapis.com/css2?family=Open+Sans&display=swap);
  
  @import url(https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200);
  
  @import url(https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css);
  
  /*! tailwindcss v3.4.11 | MIT License | https://tailwindcss.com*/
  *,
  :after,
  :before {
    border: 0 solid #e5e7eb;
    box-sizing: border-box;
  }
  :after,
  :before {
    --tw-content: "";
  }
  :host,
  html {
    line-height: 1.5;
    -webkit-text-size-adjust: 100%;
    font-family:
      Open Sans,
      ui-sans-serif,
      system-ui,
      sans-serif,
      Apple Color Emoji,
      Segoe UI Emoji,
      Segoe UI Symbol,
      Noto Color Emoji;
    font-feature-settings: normal;
    font-variation-settings: normal;
    -moz-tab-size: 4;
    tab-size: 4;
    -webkit-tap-highlight-color: transparent;
  }
  body {
    line-height: inherit;
    margin: 0;
  }
  hr {
    border-top-width: 1px;
    color: inherit;
    height: 0;
  }
  abbr:where([title]) {
    text-decoration: underline dotted;
  }
  h1,
  h2,
  h3,
  h4,
  h5,
  h6 {
    font-size: inherit;
    font-weight: inherit;
  }
  a {
    color: inherit;
    text-decoration: inherit;
  }
  b,
  strong {
    font-weight: bolder;
  }
  code,
  kbd,
  pre,
  samp {
    font-family:
      ui-monospace,
      SFMono-Regular,
      Menlo,
      Monaco,
      Consolas,
      Liberation Mono,
      Courier New,
      monospace;
    font-feature-settings: normal;
    font-size: 1em;
    font-variation-settings: normal;
  }
  small {
    font-size: 80%;
  }
  sub,
  sup {
    font-size: 75%;
    line-height: 0;
    position: relative;
    vertical-align: baseline;
  }
  sub {
    bottom: -0.25em;
  }
  sup {
    top: -0.5em;
  }
  table {
    border-collapse: collapse;
    border-color: inherit;
    text-indent: 0;
  }
  button,
  input,
  optgroup,
  select,
  textarea {
    color: inherit;
    font-family: inherit;
    font-feature-settings: inherit;
    font-size: 100%;
    font-variation-settings: inherit;
    font-weight: inherit;
    letter-spacing: inherit;
    line-height: inherit;
    margin: 0;
    padding: 0;
  }
  button,
  select {
    text-transform: none;
  }
  button,
  input:where([type="button"]),
  input:where([type="reset"]),
  input:where([type="submit"]) {
    -webkit-appearance: button;
    background-color: transparent;
    background-image: none;
  }
  :-moz-focusring {
    outline: auto;
  }
  :-moz-ui-invalid {
    box-shadow: none;
  }
  progress {
    vertical-align: baseline;
  }
  ::-webkit-inner-spin-button,
  ::-webkit-outer-spin-button {
    height: auto;
  }
  [type="search"] {
    -webkit-appearance: textfield;
    outline-offset: -2px;
  }
  ::-webkit-search-decoration {
    -webkit-appearance: none;
  }
  ::-webkit-file-upload-button {
    -webkit-appearance: button;
    font: inherit;
  }
  summary {
    display: list-item;
  }
  blockquote,
  dd,
  dl,
  figure,
  h1,
  h2,
  h3,
  h4,
  h5,
  h6,
  hr,
  p,
  pre {
    margin: 0;
  }
  fieldset {
    margin: 0;
  }
  fieldset,
  legend {
    padding: 0;
  }
  menu,
  ol,
  ul {
    list-style: none;
    margin: 0;
    padding: 0;
  }
  dialog {
    padding: 0;
  }
  textarea {
    resize: vertical;
  }
  input::placeholder,
  textarea::placeholder {
    color: #9ca3af;
    opacity: 1;
  }
  [role="button"],
  button {
    cursor: pointer;
  }
  :disabled {
    cursor: default;
  }
  audio,
  canvas,
  embed,
  iframe,
  img,
  object,
  svg,
  video {
    display: block;
    vertical-align: middle;
  }
  img,
  video {
    height: auto;
    max-width: 100%;
  }
  [hidden] {
    display: none;
  }
  *,
  :after,
  :before {
    --tw-border-spacing-x: 0;
    --tw-border-spacing-y: 0;
    --tw-translate-x: 0;
    --tw-translate-y: 0;
    --tw-rotate: 0;
    --tw-skew-x: 0;
    --tw-skew-y: 0;
    --tw-scale-x: 1;
    --tw-scale-y: 1;
    --tw-pan-x: ;
    --tw-pan-y: ;
    --tw-pinch-zoom: ;
    --tw-scroll-snap-strictness: proximity;
    --tw-gradient-from-position: ;
    --tw-gradient-via-position: ;
    --tw-gradient-to-position: ;
    --tw-ordinal: ;
    --tw-slashed-zero: ;
    --tw-numeric-figure: ;
    --tw-numeric-spacing: ;
    --tw-numeric-fraction: ;
    --tw-ring-inset: ;
    --tw-ring-offset-width: 0px;
    --tw-ring-offset-color: #fff;
    --tw-ring-color: rgba(59, 130, 246, 0.5);
    --tw-ring-offset-shadow: 0 0 #0000;
    --tw-ring-shadow: 0 0 #0000;
    --tw-shadow: 0 0 #0000;
    --tw-shadow-colored: 0 0 #0000;
    --tw-blur: ;
    --tw-brightness: ;
    --tw-contrast: ;
    --tw-grayscale: ;
    --tw-hue-rotate: ;
    --tw-invert: ;
    --tw-saturate: ;
    --tw-sepia: ;
    --tw-drop-shadow: ;
    --tw-backdrop-blur: ;
    --tw-backdrop-brightness: ;
    --tw-backdrop-contrast: ;
    --tw-backdrop-grayscale: ;
    --tw-backdrop-hue-rotate: ;
    --tw-backdrop-invert: ;
    --tw-backdrop-opacity: ;
    --tw-backdrop-saturate: ;
    --tw-backdrop-sepia: ;
    --tw-contain-size: ;
    --tw-contain-layout: ;
    --tw-contain-paint: ;
    --tw-contain-style: ;
  }
  ::backdrop {
    --tw-border-spacing-x: 0;
    --tw-border-spacing-y: 0;
    --tw-translate-x: 0;
    --tw-translate-y: 0;
    --tw-rotate: 0;
    --tw-skew-x: 0;
    --tw-skew-y: 0;
    --tw-scale-x: 1;
    --tw-scale-y: 1;
    --tw-pan-x: ;
    --tw-pan-y: ;
    --tw-pinch-zoom: ;
    --tw-scroll-snap-strictness: proximity;
    --tw-gradient-from-position: ;
    --tw-gradient-via-position: ;
    --tw-gradient-to-position: ;
    --tw-ordinal: ;
    --tw-slashed-zero: ;
    --tw-numeric-figure: ;
    --tw-numeric-spacing: ;
    --tw-numeric-fraction: ;
    --tw-ring-inset: ;
    --tw-ring-offset-width: 0px;
    --tw-ring-offset-color: #fff;
    --tw-ring-color: rgba(59, 130, 246, 0.5);
    --tw-ring-offset-shadow: 0 0 #0000;
    --tw-ring-shadow: 0 0 #0000;
    --tw-shadow: 0 0 #0000;
    --tw-shadow-colored: 0 0 #0000;
    --tw-blur: ;
    --tw-brightness: ;
    --tw-contrast: ;
    --tw-grayscale: ;
    --tw-hue-rotate: ;
    --tw-invert: ;
    --tw-saturate: ;
    --tw-sepia: ;
    --tw-drop-shadow: ;
    --tw-backdrop-blur: ;
    --tw-backdrop-brightness: ;
    --tw-backdrop-contrast: ;
    --tw-backdrop-grayscale: ;
    --tw-backdrop-hue-rotate: ;
    --tw-backdrop-invert: ;
    --tw-backdrop-opacity: ;
    --tw-backdrop-saturate: ;
    --tw-backdrop-sepia: ;
    --tw-contain-size: ;
    --tw-contain-layout: ;
    --tw-contain-paint: ;
    --tw-contain-style: ;
  }
  #webcrumbs .pointer-events-none {
    pointer-events: none;
  }
  #webcrumbs .absolute {
    position: absolute;
  }
  #webcrumbs .relative {
    position: relative;
  }
  #webcrumbs .inset-0 {
    inset: 0;
  }
  #webcrumbs .mx-auto {
    margin-left: auto;
    margin-right: auto;
  }
  #webcrumbs .mb-2 {
    margin-bottom: 8px;
  }
  #webcrumbs .mb-6 {
    margin-bottom: 24px;
  }
  #webcrumbs .mt-2 {
    margin-top: 8px;
  }
  #webcrumbs .mt-4 {
    margin-top: 16px;
  }
  #webcrumbs .flex {
    display: flex;
  }
  #webcrumbs .grid {
    display: grid;
  }
  #webcrumbs .h-\[120px\] {
    height: 120px;
  }
  #webcrumbs .h-\[150px\] {
    height: 150px;
  }
  #webcrumbs .min-h-\[800px\] {
    min-height: 800px;
  }
  #webcrumbs .w-\[150px\] {
    width: 150px;
  }
  #webcrumbs .w-full {
    width: 100%;
  }
  #webcrumbs .flex-1 {
    flex: 1 1 0%;
  }
  #webcrumbs .grid-cols-1 {
    grid-template-columns: repeat(1, minmax(0, 1fr));
  }
  #webcrumbs .flex-row {
    flex-direction: row;
  }
  #webcrumbs .flex-col {
    flex-direction: column;
  }
  #webcrumbs .flex-wrap {
    flex-wrap: wrap;
  }
  #webcrumbs .items-center {
    align-items: center;
  }
  #webcrumbs .justify-center {
    justify-content: center;
  }
  #webcrumbs .justify-between {
    justify-content: space-between;
  }
  #webcrumbs .gap-3 {
    gap: 12px;
  }
  #webcrumbs .gap-4 {
    gap: 16px;
  }
  #webcrumbs .gap-6 {
    gap: 24px;
  }
  #webcrumbs :is(.space-y-4 > :not([hidden]) ~ :not([hidden])) {
    --tw-space-y-reverse: 0;
    margin-bottom: calc(16px * var(--tw-space-y-reverse));
    margin-top: calc(16px * (1 - var(--tw-space-y-reverse)));
  }
  #webcrumbs .rounded-full {
    border-radius: 9999px;
  }
  #webcrumbs .rounded-lg {
    border-radius: 24px;
  }
  #webcrumbs .rounded-md {
    border-radius: 18px;
  }
  #webcrumbs .bg-neutral-100 {
    --tw-bg-opacity: 1;
    background-color: rgb(238 238 238 / var(--tw-bg-opacity));
  }
  #webcrumbs .bg-neutral-200 {
    --tw-bg-opacity: 1;
    background-color: rgb(224 224 224 / var(--tw-bg-opacity));
  }
  #webcrumbs .bg-primary-100 {
    --tw-bg-opacity: 1;
    background-color: rgb(233 229 255 / var(--tw-bg-opacity));
  }
  #webcrumbs .bg-white {
    --tw-bg-opacity: 1;
    background-color: rgb(255 255 255 / var(--tw-bg-opacity));
  }
  #webcrumbs .object-cover {
    object-fit: cover;
  }
  #webcrumbs .p-4 {
    padding: 16px;
  }
  #webcrumbs .p-6 {
    padding: 24px;
  }
  #webcrumbs .px-4 {
    padding-left: 16px;
    padding-right: 16px;
  }
  #webcrumbs .py-2 {
    padding-bottom: 8px;
    padding-top: 8px;
  }
  #webcrumbs .text-center {
    text-align: center;
  }
  #webcrumbs .font-title {
    font-family:
      Lato,
      ui-sans-serif,
      system-ui,
      sans-serif,
      Apple Color Emoji,
      Segoe UI Emoji,
      Segoe UI Symbol,
      Noto Color Emoji;
  }
  #webcrumbs .text-2xl {
    font-size: 24px;
    line-height: 31.200000000000003px;
  }
  #webcrumbs .text-4xl {
    font-size: 36px;
    line-height: 41.4px;
  }
  #webcrumbs .text-lg {
    font-size: 18px;
    line-height: 27px;
  }
  #webcrumbs .text-xl {
    font-size: 20px;
    line-height: 28px;
  }
  #webcrumbs .font-bold {
    font-weight: 700;
  }
  #webcrumbs .font-medium {
    font-weight: 500;
  }
  #webcrumbs .font-semibold {
    font-weight: 600;
  }
  #webcrumbs .leading-relaxed {
    line-height: 1.625;
  }
  #webcrumbs .text-neutral-600 {
    --tw-text-opacity: 1;
    color: rgb(127 127 127 / var(--tw-text-opacity));
  }
  #webcrumbs .text-neutral-700 {
    --tw-text-opacity: 1;
    color: rgb(103 103 103 / var(--tw-text-opacity));
  }
  #webcrumbs .text-neutral-950 {
    --tw-text-opacity: 1;
    color: rgb(40 40 40 / var(--tw-text-opacity));
  }
  #webcrumbs .text-primary-950 {
    --tw-text-opacity: 1;
    color: rgb(34 1 116 / var(--tw-text-opacity));
  }
  #webcrumbs .opacity-0 {
    opacity: 0;
  }
  #webcrumbs .shadow-lg {
    --tw-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1),
      0 4px 6px -4px rgba(0, 0, 0, 0.1);
    --tw-shadow-colored: 0 10px 15px -3px var(--tw-shadow-color),
      0 4px 6px -4px var(--tw-shadow-color);
  }
  #webcrumbs .shadow-lg,
  #webcrumbs .shadow-md {
    box-shadow: var(--tw-ring-offset-shadow, 0 0 #0000),
      var(--tw-ring-shadow, 0 0 #0000), var(--tw-shadow);
  }
  #webcrumbs .shadow-md {
    --tw-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1),
      0 2px 4px -2px rgba(0, 0, 0, 0.1);
    --tw-shadow-colored: 0 4px 6px -1px var(--tw-shadow-color),
      0 2px 4px -2px var(--tw-shadow-color);
  }
  #webcrumbs .transition-opacity {
    transition-duration: 0.15s;
    transition-property: opacity;
    transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
  }
  #webcrumbs .transition-transform {
    transition-duration: 0.15s;
    transition-property: transform;
    transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
  }
  #webcrumbs .duration-300 {
    transition-duration: 0.3s;
  }
  #webcrumbs .duration-500 {
    transition-duration: 0.5s;
  }
  #webcrumbs {
    font-family: Open Sans !important;
    font-size: 16px !important;
  }
  #webcrumbs :is(.bg-neutral-100) {
    color: rgba(0, 0, 0, 0.9) !important;
  }
  #webcrumbs :is(.bg-neutral-200) {
    color: rgba(0, 0, 0, 0.9) !important;
  }
  #webcrumbs :is(.bg-primary-100) {
    color: rgba(0, 0, 0, 0.9) !important;
  }
  #webcrumbs .hover\:translate-y-\[-5px\]:hover {
    --tw-translate-y: -5px;
  }
  #webcrumbs .hover\:scale-\[1\.05\]:hover,
  #webcrumbs .hover\:translate-y-\[-5px\]:hover {
    transform: translate(var(--tw-translate-x), var(--tw-translate-y))
      rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y))
      scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));
  }
  #webcrumbs .hover\:scale-\[1\.05\]:hover {
    --tw-scale-x: 1.05;
    --tw-scale-y: 1.05;
  }
  #webcrumbs .hover\:scale-\[1\.1\]:hover {
    --tw-scale-x: 1.1;
    --tw-scale-y: 1.1;
    transform: translate(var(--tw-translate-x), var(--tw-translate-y))
      rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y))
      scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));
  }
  #webcrumbs .hover\:bg-primary-200:hover {
    --tw-bg-opacity: 1;
    background-color: rgb(213 207 255 / var(--tw-bg-opacity));
  }
  #webcrumbs .hover\:shadow-xl:hover {
    --tw-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1),
      0 8px 10px -6px rgba(0, 0, 0, 0.1);
    --tw-shadow-colored: 0 20px 25px -5px var(--tw-shadow-color),
      0 8px 10px -6px var(--tw-shadow-color);
    box-shadow: var(--tw-ring-offset-shadow, 0 0 #0000),
      var(--tw-ring-shadow, 0 0 #0000), var(--tw-shadow);
  }
  #webcrumbs :is(.group:hover .group-hover\:opacity-100) {
    opacity: 1;
  }
  #webcrumbs :is(.group:hover .group-hover\:transition-none) {
    transition-property: none;
  }
  @media (min-width: 640px) {
    #webcrumbs .sm\:w-1\/4 {
      width: 25%;
    }
    #webcrumbs .sm\:grid-cols-2 {
      grid-template-columns: repeat(2, minmax(0, 1fr));
    }
    #webcrumbs .sm\:flex-row {
      flex-direction: row;
    }
    #webcrumbs .sm\:items-start {
      align-items: flex-start;
    }
    #webcrumbs .sm\:text-left {
      text-align: left;
    }
  }
  @media (min-width: 1024px) {
    #webcrumbs .lg\:grid-cols-3 {
      grid-template-columns: repeat(3, minmax(0, 1fr));
    }
  }
  
</style>
